GET http://localhost:5011/games

###
GET http://localhost:5011/games/4

###
POST http://localhost:5011/games/
Content-Type: application/json

{
    "name": "New Game",
    "genre": "Kids",
    "price": 19.99,
    "releaseDate":"2020-07-07"
}

###
PUT http://localhost:5011/games/1
Content-Type: application/json

{    
    "name": "Game11 Name",
    "genre": "Fighting1",
    "price": 9,
    "releaseDate": "1972-07-15"
}

###
DELETE http://localhost:5011/games/1


